services:
  kafka:
    image: apache/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - kafka

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
    environment:
      KAFKA_CLIENT_ID: code-engine-server
      KAFKA_BROKERS: kafka:29092
    ports:
      - 8080:3000
    depends_on:
      - kafka
    networks:
      - kafka
      - external

  worker-1:
    build:
      context: ./worker
      dockerfile: Dockerfile
      target: development
    privileged: true
    volumes:
      - ./worker:/usr/app
      - /usr/app/node_modules
    environment:
      KAFKA_CLIENT_ID: code-engine-worker-1
      KAFKA_BROKERS: kafka:29092
    depends_on:
      - kafka
    networks:
      - kafka

  worker-2:
    build:
      context: ./worker
      dockerfile: Dockerfile
      target: development
    privileged: true
    volumes:
      - ./worker:/usr/app
      - /usr/app/node_modules
    environment:
      KAFKA_CLIENT_ID: code-engine-worker-2
      KAFKA_BROKERS: kafka:29092
    depends_on:
      - kafka
    networks:
      - kafka

networks:
  kafka:
    driver: bridge
    internal: true
  external:
    driver: bridge
