export enum Status {
  PENDING = "PENDING",
  COMPILING = "COMPILING",
  COMPILED = "COMPILED",
  RUNNING = "RUNNING",
  SUCCESS = "SUCCESS",
  COMPILATION_ERROR = "COMPILATION_ERROR",
  RUNTIME_ERROR = "RUNTIME_ERROR",
}
